version: '3.8'

services:
  events-db:
    image: postgres:latest
    container_name: events_database
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - ${DOCKER_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
